unique_ids:
  assets:
    standard-page.html: S4RIFR3ZO5PLBK7UWKEMLRDQDDJKCSRX
    theme.css: KLKZRYFEPVLZOLVB46HBH55OSY25YRTL
  forms:
    iris_classifier_form: U7JS45OQICXI4OEFP5QKED5J4IAAENWW
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: UFWLOVGGMQPQP5GEFD2Y22EJH4HR6YBZ
